name: Run Shell Script

on:
  push:
    branches:
      - main
      - lab3A
      - lab3B
      - lab3C
      - lab3D
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up permissions
        run: chmod +x src/raft/runtest.sh # 确保你的脚本有执行权限

      - name: Run shell script
        run: ./src/raft/runtest.sh 3A 10
